[package]
name = "day04"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = { version = "0.22.0" }

[dependencies]
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }
common = { path = "../common"}
