[package]
name = "day05"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common"}
num-format = { version = "0.4.4", features = ["with-system-locale"] }
tokio = { version = "1.41.1", features = ["full"] }
